#!/bin/bash

numberArray=()

echo "How many numbers would like to sort: "
read AmountOfNumbers

echo "Please enter the numbers: "
for (( i=0; i<$AmountOfNumbers; i++ ))
do
  read number 
  numberArray[i]+=$number
done

x=0

for (( k=0; k<$AmountOfNumbers; k++ ))
do
  for (( l=k; l>=0; l-- ))
  do
    if [ "${numberArray[k-x]}" -lt "${numberArray[l]}" ]; then
      numberSwitch=${numberArray[k-x]}
      numberArray[k-x]=${numberArray[l]}
      numberArray[l]=$numberSwitch
      (( x++ ))
    fi
  done
  x=0
done

echo "Sorted numbers: "
for (( j=0; j<$AmountOfNumbers; j++ ))
do 
  echo "${numberArray[j]}"
done

