#!/bin/bash

numberArray=()

echo "How many numbers would like to sort: "
read AmountOfNumbers

indexedNumber=$((AmountOfNumbers-1))

echo "Please enter the numbers: "
for (( i=0; i<$AmountOfNumbers; i++ ))
do
  read number 
  numberArray[i]+=$number
done

for (( k=1; k<$AmountOfNumbers; k++ ))
do
  for (( l=k; l>=0; l-- ))
  do
    if [ "${numberArray[k]}" -lt "${numberArray[l]}" ]; then
      numberSwitch=${numberArray[k]}
      numberArray[k]=${numberArray[l]}
      numberArray[l]=$numberSwitch
    fi
  done
done

echo "Sorted numbers: "
for (( j=0; j<$AmountOfNumbers; j++ ))
do 
  echo "${numberArray[j]}"
done

